### ISSUE TITLE
Instructor feedback - week 2

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [amgenz15/foodieGrubProject#1]
Hi @amgenz15! I'm really excited to see this project come together! 

Remember to add the project problem statement and time log. 
![Screen Shot 2023-01-31 at 2 14 03 PM](https://user-images.githubusercontent.com/13874466/215884808-9433cb0d-44a2-41e5-bb98-61b8df3b73dd.png)

**Comment by amgenz15** [comment]
@pawaitemadisoncollege I believe my project is ready for checkpoint #1!

**Comment by pawaitemadisoncollege** [comment]
Hi @amgenz15! This is going to be such a fun project to build with a focus on the recipe and not all the advertising stuff that is on so many recipe sites!

Your problem statement, time log, user stories and screens are all looking good. I think you've scoped your project really well  in terms of what should be doable this semester.

I always like to compare the user stories with the project objectives to make sure they match:

- [x] In terms of DB CRUD (create-read-update-delete), I think read, create/insert and update are represented, but I don't think there is a Delete scenario. Would adding the ability to delete a recipe make sense?
- [x] There's reference to specifying a category in the user stories, I think that is called "topic" in the wireframes? I was wondering where the category or topic will be specified on the recipe? One category? Multiples? Will the user define the category name or will there be a set list of them in the application?
- [x] One objective of the indie project is to implement an api or web service. Do you have any thoughts as to what you might use? I think we discussed a few ideas in Slack #indie-project-pitch, but there are other options too.  If this is already represented in your user stories/screens let me know!

You are off to a great start!!!

**Comment by pawaitemadisoncollege** [comment]
One more thing - you've done a good job laying out the project plan!  I suspect you'll have more detail to add as you learn more, but I can actually help you remove something! EJBs will only be implemented in a weekly exercise; I don't anticipate it fitting in with your project (they are not required to be part of the project).
